{{- if .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "asv.controllerServiceAccountName" . }}
  labels:
    {{- include "asv.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.rbac.kubernetesAdapter.enabled }}
---
{{- end }}
{{- if .Values.serviceAccount.probe.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "asv.probeServiceAccountName" . }}
  labels:
    {{- include "asv.labels" . | nindent 4 }}
    app.kubernetes.io/component: probe
  {{- with .Values.serviceAccount.probe.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

